### ISSUE TITLE
Fix typo Js.Json.object_

### ISSUE THREAD

**Issue by strdr4605** [rescript-lang/bucklescript.github.io#136]
There is a typo  (missing **c** in object word) on page https://bucklescript.github.io/bucklescript/api/Js.Json.html

```ocaml
val object_ : t Js_dict.t -> t
object_ dict makes a JSON objet of the Js.Dict.t dict
```
to
```ocaml
val object_ : t Js_dict.t -> t
object_ dict makes a JSON object of the Js.Dict.t dict
```

Wanted to submit a pull request but did not found the file in this repo.

**Comment by bobzhang** [comment]
fixed in https://github.com/BuckleScript/bucklescript/pull/3617
sorry for the slow response
