### ISSUE TITLE
6 broken links and a couple of other issues

### ISSUE THREAD

**Issue by ShalokShalom** [rescript-lang/bucklescript.github.io#2]
A couple of links are broken here: https://www.techatbloomberg.com/blog/bucklescript-1-0-release-arrived/

> _Hello world_ 
> _examples of calling JS libraries_ 
> _The playground_
> _FFI_ 

The link for the FFI changed, so it directs now to the header of the manual as a fallback, 
instead to [the FFI section](https://bucklescript.github.io/bucklescript/Manual.html#_ffi)

Plus, the Github button on this page leads to a complete different repo, 
namely that one of Bloomberg instead of the Bucklescript one. 

When somebody likes to visit your Homepage at https://bucklescript.github.io, redirects that to the manual instead to the actual Homepage, the link to the Blog does an intermediate step to a pointless page between and there is a space missing on the homepage.

**Comment by ShalokShalom** [comment]
This one reads also a bit spooky: 

> Facebook revealed that OCaml generated using Reason and BuckleScript powers 25 percent of messenger.com.

https://www.techatbloomberg.com/blog/release-1-7-story-behind-bucklescript/

**Comment by chenglou** [comment]
Unfortunately we can't touch those links anymore. We fixed whatever we can here. For the github links, I wish the post pointed to hashes, not master
