### ISSUE TITLE
bs.raw Example produces compiler warnings

### ISSUE THREAD

**Issue by scull7** [rescript-lang/bucklescript.github.io#36]
When I copy and paste the example code into the playground I receive compiler warnings:

>File "", line 9, characters 20-21: Warning 20: this argument will not be used by the function. File "", line 9, characters 22-23: Warning 20: this argument will not be used by the function. 

version: `// Generated by BUCKLESCRIPT VERSION 2.2.4, PLEASE EDIT WITH CARE`

https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhgJjEF4IG0CkAnKB3CBvAPgFAQQBmArgHYDGYAlgPaUAUUANBAEYCUexJEakwDODUADpgDAObMARAAsQwKWXQMAthEw4AUlABuUAMrV0dAA5gAhHO4BufiXThy6StAgBqLvwC+hPh+ALqOhLrCkjKscMwAjBwATNwOQA

Is this expected?

**Comment by chenglou** [comment]
Yeah kinda, see https://github.com/BuckleScript/bucklescript/issues/2682

I'll merge this one into it. Thanks!
